export const bankList = [
  { codigo: "0102", nombre: "Banco de Venezuela" },
  { codigo: "0104", nombre: "Venezolano de Crédito" },
  { codigo: "0105", nombre: "Banco Mercantil" },
  { codigo: "0108", nombre: "Banco Provincial" },
  { codigo: "0114", nombre: "Bancaribe" },
  { codigo: "0115", nombre: "Banco Exterior" },
  { codigo: "0116", nombre: "Banco Occidental de Descuento (BOD)" },
  { codigo: "0128", nombre: "Banco Caroní" },
  { codigo: "0134", nombre: "Banesco" },
  { codigo: "0137", nombre: "Banco Sofitasa" },
  { codigo: "0138", nombre: "Banco Plaza" },
  { codigo: "0151", nombre: "BFC Banco Fondo Común" },
  { codigo: "0156", nombre: "100% Banco" },
  { codigo: "0157", nombre: "DelSur Banco Universal" },
  { codigo: "0163", nombre: "Banco del Tesoro" },
  { codigo: "0166", nombre: "Banco Agrícola de Venezuela" },
  { codigo: "0168", nombre: "Bancrecer" },
  { codigo: "0169", nombre: "Mi Banco" },
  { codigo: "0171", nombre: "Banco Activo" },
  { codigo: "0172", nombre: "Bancamiga Banco Microfinanciero" },
  { codigo: "0173", nombre: "Banco Internacional de Desarrollo" },
  { codigo: "0174", nombre: "Banplus Banco Universal" },
  { codigo: "0175", nombre: "Banco Bicentenario del Pueblo" },
  { codigo: "0177", nombre: "Banco de la Fuerza Armada Nacional Bolivariana" },
  { codigo: "0190", nombre: "Citibank" },
  { codigo: "0191", nombre: "Banco Nacional de Crédito (BNC)" }
];
